-- Your SQL goes here
CREATE TABLE images (
  id UUID PRIMARY KEY,
  date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  upload_by UUID REFERENCES users(id),
  md5 VARCHAR DEFAULT NULL,
  origin_filename VARCHAR DEFAULT NULL
)